services:
  favlit-users-api:
    container_name: favlit_users_api
    image: users-api-image
    healthcheck:
      interval: 10s
      retries: 6
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/api/health
      timeout: 10s
    ports:
      - 14000:80
    depends_on:
      favlit-users-db:
        condition: service_healthy

  favlit-users-db:
    container_name: favlit_users_db
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: "fav_lit_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 14432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  favlit-works-api:
    container_name: favlit_works_api
    image: works-api-image
    healthcheck:
      interval: 10s
      retries: 6
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/api/health
      timeout: 10s
    ports:
      - 15000:80
    depends_on:
      favlit-works-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  favlit-works-db:
    container_name: favlit_works_db
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: "fav_lit_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 15432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  favlit-moderation-api:
    container_name: favlit_moderation_api
    image: moderation-api-image
    healthcheck:
      interval: 10s
      retries: 6
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/api/health
      timeout: 10s
    ports:
      - 16000:80
    depends_on:
      favlit-moderation-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  favlit-moderation-db:
    container_name: favlit_moderation_db
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: "fav_lit_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 16432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  influxdb:
    container_name: influxdb
    image: influxdb:1.8.10
    environment:
      - "INFLUXDB_DB=krakend"
      - "INFLUXDB_USER=krakend-dev"
      - "INFLUXDB_USER_PASSWORD=pas5w0rd"
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=supersecretpassword"
    ports:
      - 8086:8086

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: RabbitMQ
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  krakend:
    container_name: KrakenD
    image: devopsfaith/krakend
    ports:
      - 8080:8080
    command: [ "run", "-d", "-c", "/etc/krakend/krakend.json" ]
    volumes:
      - ./krakend:/etc/krakend/
    healthcheck:
      interval: 1m30s
      retries: 3
      test:
        - CMD
        - curl
        - -f
        - http://localhost
      timeout: 10s
    depends_on:
      - favlit-users-api
      - favlit-works-api
      - favlit-moderation-api